config/routes.rb
Rails.application.routes.draw do

	resources :users do
		member do
			get :following, :followers
		end
	end	
	resources :sessions, 	 only: [:new, :create, :destroy]
	resources :posts do
		resources :comments, module: :posts 
	end
	resources :comments do
		resources :comments, module: :comments
	end
	resources :relationships, only: [:create, :destroy]

	root 'pages#index'
	match '/signup',  to: 'users#new', 	  		via: 'get'
	match '/signin',  to: 'sessions#new', 		via: 'get'
	match '/signout', to: 'sessions#destroy',	via: 'delete'
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_many :comments, as: :commentable, dependent: :destroy
	belongs_to :commentable, polymorphic: true, optional: true
	belongs_to :user
end

app/controllers/comments/comments_controller.rb
class Comments::CommentsController < CommentsController
	
	private

		def set_commentable
			@commentable = Comment.find(params[:comment_id])
		end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :signed_in_user
	before_action :correct_user, only: :destroy
	before_action :set_commentable, only: :create


	def new
	  @comment = Comment.new(params[:comment])
	end

	def create
		@comment = @commentable.comments.new comment_params
		@comment.user = current_user
		if @comment.save
			redirect_to root_url, notice: 'Your comment was created'
		else
			render current_user
		end	 
	end

	def destroy
		@comment.destroy
		respond_to do |format|
			format.html { redirect_to current_user }
			format.js
		end
	end

	def edit
		# @comment = @commentable.comments.find(params[:id])
    @comment = Comment.find(params[:id])
  end

  def update
  	@comment = Comment.find(params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to current_user
    else
      render 'edit'
    end
  end

	private

		def comment_params
			params.require(:comment).permit(:body)
		end

		def correct_user
      @comment = current_user.comments.find(params[:id])
      redirect_to root_url if @comment.nil?
    end

end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
	private

		def set_commentable
			@commentable = Post.find(params[:post_id])
		end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_form.html.erb
  <div class="row">
  	<div class="col s12">
  		<%= form_for [commentable, Comment.new] do |f| %>
        <div class="input-field">
          <%= f.text_area :body, class: 'materialize-textarea', placeholder: 'Left your comment here' %>		
        </div>
        <button type="submit" class="btn-flat waves-effect waves-light">
        	Comment
        	<i class="material-icons right">send</i>
        </button>
      </div>
    <% end %>
  </div>

app/views/comments/_comments.html.erb
<% commentable.comments.each do |comment| %>
	<div class="row" id="comment_<%= comment.id %>">
	  <div class="col s12">
	  	<div class="col s1">
	  		<!-- image here	 -->
	  		<%= image_tag(comment.user.avatar.url, class: "circle responsive-img")%>
	  	</div>
	  	<div class="col s10">
	  		<div>
		  			<%= link_to comment.user.name, comment.user %>
		  			<span class="thin">
		  				commented <%= time_ago_in_words(comment.created_at) %> ago
		  			</span>
		  	</div>
		  	<div>
		  		<%= comment.body %>
		  	</div>	
		  	

		  	<div>
		  		<%= render 'comments/comment_form', commentable: comment %>
		  	</div>
	  	</div>
	  	<div class="col s1">
	  		<!-- delete button here -->
	  		<% if current_user?(comment.user) %>
	  			<div>
	          <%= link_to comment, method: :delete, data: { confirm: "You sure?" },
	                                                title: comment.body, 
	                                                remote: true  do %>
	            <i class="material-icons valign-wrapper">delete</i>
	          <% end %>
	  			</div>
	  			<div>
        		<%= link_to edit_comment_path(comment), commentable: comment  do%>
							<i class="material-icons valign-wrapper">edit</i>
        		<% end %>
	  			</div>
        <% end %>
	  	</div>
		  
	  </div>
	</div>
	<div class="row">
		<div class="col s10 offset-s1">
			<%= render 'comments/comments', commentable: comment %>
		</div>
	</div>
<% end %>	

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/comments/edit.html.erb
<h5>Edit comment</h5>
  <div class="row">
  	<div class="col s12">
  		<%= form_for (@comment) do |f| %>
        <div class="input-field">
          <%= f.text_area :body, class: 'materialize-textarea', placeholder: 'Left your comment here' %>		
        </div>
        <button type="submit" class="btn-flat waves-effect waves-light">
        	Comment
        	<i class="material-icons right">send</i>
        </button>
      </div>
    <% end %>
  </div>