config/routes.rb
Rails.application.routes.draw do

	resources :users do
		member do
			get :following, :followers
		end
	end	
	resources :sessions, 	 only: [:new, :create, :destroy]
	resources :posts do
		resources :comments, module: :posts 
	end
	resources :comments do
		resources :comments, module: :comments
	end
	resources :relationships, only: [:create, :destroy]

	root 'pages#index'
	match '/signup',  to: 'users#new', 	  		via: 'get'
	match '/signin',  to: 'sessions#new', 		via: 'get'
	match '/signout', to: 'sessions#destroy',	via: 'delete'
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, as: :commentable, dependent: :destroy
	default_scope -> { order('created_at DESC') }
	validates :content, presence: true
	validates :user_id, presence: true

	def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
	private

		def set_commentable
			@commentable = Post.find(params[:post_id])
		end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :signed_in_user
	before_action :correct_user,   only: :destroy

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to root_url
		end
	end

	def destroy
		@post.destroy
		respond_to do |format|
			format.html { redirect_to current_user }
			format.js
		end
	end

	def edit
    @post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to current_user
    else
      render 'edit'
    end
  end

	private
		def post_params
			params.require(:post).permit(:content)
		end

		def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="card col s12" <div id="post_<%= post.id %>">
  <div class="card-content">
    <!-- post here         -->
    <div class="row">
      <div class="col l1 s3">
        <%= image_tag(@user.avatar.url, class: "circle responsive-img")%>
      </div>
      <div class="col l10 s8">
        <strong>
          <span>
            <a href="<%= @user %>">
              <%= @user.name %>
            </a>
          </span>
          <span class="thin">
            posted <%= time_ago_in_words(post.created_at) %> ago
          </span>
        </strong>
        <div>
          <%= post.content %>
        </div>
        <%= render 'comments/comment_form', commentable: post %>
      </div>
      <div class="col s1">
        <% if current_user?(post.user) %>
          <div>
            <%= link_to post, method: :delete, data: { confirm: "You sure?" },
                                               title: post.content, 
                                               remote: true  do %>
              <i class="material-icons valign-wrapper">delete</i>
            <% end %>
          </div>
          <div>
            <%= link_to edit_post_path(post), commentable: post  do%>
              <i class="material-icons valign-wrapper">edit</i>
            <% end %>
          </div>
        <% end %>
      </div>
      
    </div>
    <div>
    </div>
    
  </div>
  <% if post.comments.any? %>
    <div class="card-action">
      <!-- comments here -->
      <h5>Comments</h5>
      <div class="row">
        <%= render 'comments/comments', commentable: post %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_post_form.html.erb
<div class="col s12">
  <%= form_for(@post) do |f| %>
    <div class="row">
      <div class="input-field">
        <%= f.text_area :content, class: 'materialize-textarea' %>  
        <%= f.label :content, "What's on your mind?" %> 
      </div>
      <button type="submit" class="btn waves-effect waves-light">
        Post
        <i class="material-icons right">send</i>
      </button>
    </div>
  <% end %>
</div>

app/views/posts/destroy.js.erb
$('#post_<%= @post.id %>').remove();

app/views/posts/edit.html.erb
<h5>Edit post</h5>
<%= render "posts/post_form" %>