config/routes.rb
Rails.application.routes.draw do

	resources :users do
		member do
			get :following, :followers
		end
	end	
	resources :sessions, 	 only: [:new, :create, :destroy]
	resources :posts do
		resources :comments, module: :posts 
	end
	resources :comments do
		resources :comments, module: :comments
	end
	resources :relationships, only: [:create, :destroy]

	root 'pages#index'
	match '/signup',  to: 'users#new', 	  		via: 'get'
	match '/signin',  to: 'sessions#new', 		via: 'get'
	match '/signout', to: 'sessions#destroy',	via: 'delete'
end

app/views/layouts/_feed.html.erb
<% if @feed_items %>
   <%= render partial: 'layouts/feed_item', collection: @feed_items %>
<% end %>

app/views/layouts/_feed_item.html.erb
<div class="card col s12">
  <div class="card-content">
    <!-- post here         -->
    <div class="row">
      <div class="col l2 s3">
        <%= image_tag(feed_item.user.avatar.url, class: "circle responsive-img")%>
      </div>
      <div class="col l10 s8">
        <strong><%= link_to feed_item.user.name, feed_item.user %></strong>
        <div>
          <%= feed_item.content %>
        </div>

        <div class="thin">
         <%= time_ago_in_words(feed_item.created_at) %> ago
        </div>
        <%= render 'comments/comment_form', commentable: feed_item %>
      </div>
   
      
    </div>
  </div>

  <% if feed_item.comments.any? %>
    <div class="card-action">
      <!-- comments here -->
      <h5>Comments</h5>
      <div class="row">
        <%= render 'comments/comments', commentable: feed_item %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
     
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="nav-extended">
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to 'Blog', root_path, class: "brand-logo" %>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        
        <ul class="right hide-on-med-and-down">
          <li><%= link_to "Users", users_path %></li>
          <% if signed_in? %>
          <!-- dropdown -->
          <ul id="dropdown1" class="dropdown-content">
            <li><%= link_to 'Profile', current_user %></li>
            <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign out', signout_path, method: "delete" %></li>
          </ul>

          <li>
            <a class="dropdown-button" href="#!" data-activates="dropdown1">
              <i class="material-icons right">arrow_drop_down</i><%= current_user.name %>
            </a>
          </li>
          <% else %>
            <li><%= link_to 'Sign in', signin_path %></li>
          <% end %>
        </ul>

        <!-- side-nav  -->
        <ul class="side-nav" id="mobile-demo">
          <li><%= link_to "Users", users_path %></li>
        <% if signed_in? %>
          <!-- dropdown -->
            <li><%= link_to 'Profile', current_user %></li>
            <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign out', signout_path, method: "delete" %></li>
          
          <% else %>
            <li><%= link_to 'Sign in', signin_path %></li>
          <% end %>
        </ul>

        
      </div>
    </div>
  </nav>
</header>

<script type="text/javascript">
   $(".button-collapse").sideNav();
</script>

app/views/layouts/_user_form.html.erb
<div class="row">
  <div class="col s12 m8 l6 offset-l3 offset-m2">
    <%= form_for @user, html: { multipart: true } do |f| %>

      <div class="input-field">
        <i class="material-icons prefix">account_circle</i>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="input-field">
        <i class="material-icons prefix">email</i>
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>

      <div class="input-field">
        <i class="material-icons prefix">vpn_key</i>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>

      <div class="input-field">
        <i class="material-icons prefix"></i>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>


     
      
      <div class="input-field center-align">
        <% if signed_in? %>
           <div class="file-field input-field">
            <div class="btn">
              <span>File</span>
              <%= f.file_field :avatar  %>
            </div>
            <div class="file-path-wrapper">
              <input class="file-path validate" type="text">
            </div>
          </div>
          <%= f.submit "Edit profile", class: "waves-effect waves-light btn" %>
        <% else %>
          <%= f.submit "Create account", class: "waves-effect waves-light btn" %>
        <% end %>
      </div>
    
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
		<%= render 'layouts/header' %>
		<div class="container">
    	<%= yield %>
		</div>
  </body>
</html>